content for 2025-01-17-doom
omarkohl/rationality-freiburg.de pull request #8
Opened 2024-12-18 10:11 UTC by angelo-fuchs

2024-12-19 08:19 UTC, omarkohl requested changes
almost perfect :slightly_smiling_face:

2024-12-19 08:19 UTC, omarkohl commented on website/content/events/2025-01-17-doom/_index.md
> +description: "Where: Haus des Engagements, Rehlingstraße 9, 79100 Freiburg. When: Friday, December 20th 2024 at 18:00 hours CET."
Date wrong. I know it's annoying to set it in two places :-(

2024-12-19 08:19 UTC, omarkohl commented on website/content/events/2025-01-17-doom/_index.de.md
> +description: "Wo: Haus des Engagements, Rehlingstraße 9, 79100 Freiburg. Wann: Freitag, 20. Dezember 2024 um 18:00 Uhr MEZ."
See other comment

2024-12-19 08:19 UTC, omarkohl commented on website/content/events/2025-01-17-doom/_index.de.md
> +[ACX - The Extinction Tournament](https://www.astralcodexten.com/p/the-extinction-tournament)
optional: highlight that the link is in English e.g by appending "(Englisch)".

2024-12-19 08:19 UTC, omarkohl commented on website/content/events/2025-01-17-doom/_index.de.md
> +Dieses Treffen wird von Omar moderiert.
Ben

2024-12-19 16:58 UTC, angelo-fuchs commented
@omarkohl I integrated all your comments.

2024-12-20 08:50 UTC, omarkohl approved these changes
lgtm

2024-12-20 08:50 UTC, merged